BaseBoxLayout:
    spacing: [0,0]
    # canvas.before:
    #     Color:
    #         rgba: 0.13, 0.13, 0.13, 1
    #     Rectangle:
    #         pos: self.pos
    #         size: self.size
    cols: 1
    
    Button:
        size_hint_y: None
        height: 20
        text: "1"
    Button:
        size_hint_y: None
        height: 20
        text: "2"
    Button:
        size_hint_y: None
        height: 20
        text: "3"
    Button:
        size_hint_y: None
        height: 20
        text: "4"
    Button:
        size_hint_y: None
        height: 20
        text: "5"
    Button:
        size_hint_y: None
        height: 20
        text: "6"