BoxLayout:
    orientation: 'vertical'
    Label:
        id: label
        size_hint_y: .3
        font_size: 24
        text: "Hello, ZhaoYue! you can get 4.2 months year-end bonus."
    ScrollView:
        size_hint_y: .5
        GridLayout:
            cols: 1
            id: target
            size_hint: 1, None
            height: self.minimum_height
    Button:
        text: "Click to receive now!!"
        on_release: app.screenshot_button(root.ids.target)
