MouseBox:
    orientation: 'horizontal'
    padding: 10
    MouseFloat:
        id: mouse_float
        size_hint: None, None
        size: 200, 500
        canvas.before:
            Color:
                rgba: 1, 0, 0, 1
            Line:
                width: 1
                rectangle: self.x, self.y, self.width, self.height
    BoxLayout:
        Button:
            id: disabled_choose_btn
            size_hint: None, None
            size: 100, 50
            text: "Change Disabled"
            on_release: mouse_float.OnChooseDisbaledBtnDown()
